# Generated by Django 5.2.8 on 2025-11-14 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('summary', models.TextField()),
                ('detailed_explanation', models.TextField(blank=True)),
                ('interactive_widget_key', models.CharField(blank=True, help_text='Key used by the frontend JS to hook into this concept', max_length=100)),
                ('category', models.CharField(blank=True, help_text='e.g. peopleware, measurement, risk, productivity', max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('source', models.CharField(blank=True, max_length=200)),
                ('year', models.PositiveIntegerField(blank=True, null=True)),
                ('theme', models.CharField(blank=True, help_text='e.g. measurement, peopleware, risk, productivity', max_length=100)),
            ],
            options={
                'ordering': ['theme', 'year'],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('life', 'Life'), ('career', 'Career'), ('publication', 'Publication'), ('other', 'Other')], default='career', max_length=20)),
                ('order_in_year', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['year', 'order_in_year'],
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('year_published', models.PositiveIntegerField(blank=True, null=True)),
                ('work_type', models.CharField(choices=[('book', 'Book'), ('article', 'Article'), ('paper', 'Paper / Report')], default='book', max_length=20)),
                ('description', models.TextField()),
                ('key_ideas', models.TextField(help_text='Summarize the core ideas and themes')),
                ('impact', models.TextField(help_text='Describe its impact on software engineering')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'ordering': ['year_published', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Influence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('influence_type', models.CharField(choices=[('person', 'Person'), ('book', 'Book'), ('practice', 'Practice / Method'), ('field', 'Field / Movement')], default='person', max_length=20)),
                ('description', models.TextField()),
                ('weight', models.PositiveIntegerField(default=1, help_text='Rough strength of the influence (1–10)')),
                ('related_work', models.ManyToManyField(blank=True, to='bio.work')),
            ],
            options={
                'ordering': ['-weight', 'name'],
            },
        ),
    ]
